name: Send Email

on: [push]  # Trigger the workflow on push events

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your desired Python version
      - name: Install dependencies
        run: pip install -r requirements.txt  # If you have any external dependencies
      - name: Send email
        run: python send_email.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
